### ISSUE TITLE
Add the ability to configure Jersey Client

### ISSUE THREAD

**Issue by rmcdouga** [hanleyt/jersey-junit#1]
JerseyTest provides the hook for configuring advanced client settings by overriding the configureClient method of JerseyTest.  It would be nice if a test using JerseyExtension could provide an updated ClientConfig.

I've forked your project and made the changes to the JerseyExtension class.  The code is relatively trivial.

P.S.  Thanks for writing this and making it available.

**Comment by hanleyt** [comment]
Hey Rob,

Sounds great, thanks for the contribution.

If you create a PR I'll be happy to help getting this merged.

Thanks!

**Comment by rmcdouga** [comment]
OK, will do.  Quick question:

I had some trouble with the com.google.common.truth.Truth dependency.  To get around this, I had to convert the Unit tests to just use standard JUnit5 assertions (org.junit.jupiter.api.Assertions).  I'm not sure if you want that version or not.  I could:
1) Just include the main code without unit tests in the PR
2) Include both the main code and the modified unit tests (that use JUnit Assertions) in the PR
3) Try and mock up a version of the unit tests that using the com.google assertions but these would be untested (they would compile but I can't run them)

Do you have a preference?  I'm thinking #2 since you'd get everything I've modified.  You can then decide what the final result should look, but I wanted to check first...

**Comment by rmcdouga** [comment]
One more thing:  You provide two constructors for JerseyExtension, one that takes a Supplier<Application> and one that takes a Function<ExtensionContext, Application>.  I'm added two additional overloaded constructors that take BiFunction<ExtensionContext, ClientConfig, ClientConfig> to each of the previous two.  I haven't added any additional that take Function<ClientConfig, ClientConfig> instead of the BiFunction<> because I didn't want to go too wild with the overloading.  If you feel differently, feel free to add them.  At some point, the overloading should probably give way to a Builder object instead.  What that point is can be a matter of debate, so I erred on the side of keeping the overloading to a minimum.

**Comment by tomashanley-toast** [comment]
yeah sounds good about the overloading. A builder might be needed at some stage but what you've done is fine for now. Thanks!
I commented on the PR about the google.truth issue.

**Comment by hanleyt** [comment]
Fixed by  PR #2
