### ISSUE TITLE
Deploy to Maven Central

### ISSUE THREAD

**Issue by pmwmedia** [hanleyt/jersey-junit#3]
Could you deploy the Maven artifacts also to Maven Central? This will simply the usage a lot, if you have to use a very strict company proxy.

**Comment by hanleyt** [comment]
Hey Martin, sure, I’ll look into that and let you know when it’s done!

**Comment by eddarmitage** [comment]
Is this likely to happen? I'm in the same boat, in so much as I'd like to use this extension but can't get at it because it's not proxied to our internal repo.

**Comment by tomashanley-toast** [comment]
hey, 
Apologies about the delay on this.
I started the process but didn't get it finished. 
I'll have a go at finishing it this weekend.
Thanks,
Tom

**Comment by hanleyt** [comment]
Hey everyone,

Apologies this took me sooo long to get around to, the process is a bit awkward, but its done now!

The PR with the config changes is here #11 if you're interested, but version 2.1.0 has already been uploaded.

Thanks for your patience! 
Tom
