### ISSUE TITLE
Bumping jersey version to 2.28

### ISSUE THREAD

**Issue by grunenwflorian** [hanleyt/jersey-junit#6]
Hey Tomas,

First, thanks for the library !
Second, would it be possible to upgrade the jersey version to 2.28 and release it ?
2.28 was released by the eclipse foundation and contains some bug fixes.

Regards,

**Comment by hanleyt** [comment]
Hey @grunenwflorian
I've updated the jersey version to 2.28 in #7 and created a new release `1.3.0`
Hope all is well!
Tomas

**Comment by grunenwflorian** [comment]
All good and thanks a lot !
